flipkart/app/urls.py
from . import views
from django.urls import path

app_name = 'app'

urlpatterns = [
    path('', views.all_product, name='all_category'),
    path('<slug:c_slug>/', views.all_product, name='product_by_category'),
    path('<slug:c_slug>/<slug:pro_slug>/', views.pro_details, name='pro_details'),
]

flipkart/cart/urls.py
from django.urls import path
from . import views

app_name = "cart"

urlpatterns = [
    path('', views.cart_details, name='cart_details'),
    path('add/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove/<int:product_id>/', views.cart_minus, name='cart_minus'),
    path('delete/<int:product_id>/', views.delete, name='delete')
]

flipkart/flipkart/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/', include('app.urls')),
    path('search/', include('search.urls')),
    path('cart/', include('cart.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

flipkart/search/urls.py
from django.urls import path
from . import views

app_name = "search"

urlpatterns=[
    path('', views.search_result, name='search_result')
]

flipkart/app/models.py
from django.db import models
from django.urls import reverse


# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    desc = models.TextField(blank=True)
    image = models.ImageField(upload_to='category', blank=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def get_url(self):
        return reverse('app:product_by_category', args=[self.slug])

    def __str__(self):
        return '{}'.format(self.name)


class Product(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    desc = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.IntegerField()
    image = models.ImageField(upload_to='product', blank=True)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    class Meta:
        ordering = ('name',)
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def get_url(self):
        return reverse('app:pro_details', args=[self.category.slug, self.slug])


    def __str__(self):
        return '{}'.format(self.name)

flipkart/cart/models.py
from django.db import models
from app.models import Product


# Create your models here.
class Cart(models.Model):
    cid = models.CharField(max_length=250, blank=True)
    date_added = models.DateField(auto_now_add=True)

    class Meta:
        db_table = 'Cart'
        ordering = ['date_added']

    def __str__(self):
        return self.cid


class CartItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    active = models.BooleanField(default=True)

    class Meta:
        db_table = 'CartItem'

    def sub_total(self):
        return self.product.price * self.quantity

    def __str__(self):
        return self.product

flipkart/search/models.py
from django.db import models

# Create your models here.

flipkart/app/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from django.core.paginator import Paginator,EmptyPage,InvalidPage

# Create your views here.


def all_product(request, c_slug=None):
    c_page = None
    products_list = None
    if c_slug != None:
        c_page = get_object_or_404(Category, slug=c_slug)
        products_list = Product.objects.all().filter(category=c_page, available=True)
    else:
        products_list = Product.objects.all().filter(available=True)
    paginator=Paginator(products_list,6)
    try:
        page=int(request.Get.get('page',1))
    except:
        page=1
    try:
        products=paginator.page(page)
    except(EmptyPage,InvalidPage):
        products=paginator.page(paginator.num_pages)
    return render(request, 'category.html', {'categorys': c_page, 'products': products})


def pro_details(request, c_slug, pro_slug):
    try:
        product = Product.objects.get(category__slug=c_slug, slug=pro_slug)
    except Exception as e:
        raise e
    return render(request, 'product.html', {'product': product})

flipkart/cart/views.py
from django.shortcuts import render, get_object_or_404
from django.shortcuts import redirect
from app.models import Product
from .models import Cart, CartItem
from django.core.exceptions import ObjectDoesNotExist


# Create your views here.


def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart


def add_to_cart(request, product_id):
    product = Product.objects.get(id=product_id)
    try:
        cart = Cart.objects.get(cid=_cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(
            cid=_cart_id(request)
        )
        cart.save()
    try:
        cart_item = CartItem.objects.get(product=product, cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity += 1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(
            product=product,
            quantity=1,
            cart=cart
        )
        cart_item.save()
    return redirect('cart:cart_details')


def cart_details(request, total=0, counter=0, cart_item=None):
    try:
        cart = Cart.objects.get(cid=_cart_id(request))
        cart_item = CartItem.objects.filter(cart=cart, active=True)
        for item in cart_item:
            total += (item.product.price * item.quantity)
            counter += item.quantity
    except ObjectDoesNotExist:
        pass
    return render(request, 'cart.html', dict(cart_item=cart_item, total=total, counter=counter))


def cart_minus(request,product_id):
    cart = Cart.objects.get(cid=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_details')


def delete(request, product_id):
    cart = Cart.objects.get(cid=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    cart_item.delete()
    return redirect('cart:cart_details')

flipkart/search/views.py
from django.shortcuts import render
from app.models import Product
from django.db.models import Q


# Create your views here.

def search_result(request):
    product = None
    query = None
    if 'q' in request.GET:
        query = request.GET.get('q')
        products = Product.objects.all().filter(Q(name__contains=query) | Q(desc__contains=query))
        return render(request, 'search.html', {'query': query, 'product': products})

flipkart/templates/base.html
{% load static %}
<!DOCTYPE html>
    <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <link rel="preconnect" href="https://fonts.googleapis.com">
            <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
            <link href="https://fonts.googleapis.com/css2?family=Roboto:ital@1&display=swap" rel="stylesheet">
            <link rel="stylesheet" href="{% static 'css/custome.css' %}" >
            <link href="{% static 'css/fontawesome.min.css' %}" rel="stylesheet">
            <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" >
            <script src="https://kit.fontawesome.com/a076d05399.js"></script>
            <meta name="description" content="{% block metadescription %}{% endblock %}">
            <title>{% block title %}{% endblock %}</title>
        </head>
        <body>
            <div class="container">
                {% include 'header.html' %}
                {% include 'navbar.html' %}
                {% block content %}
                {% endblock %}
            </div>
            {% include 'footer.html' %}
            <script src="{% static 'jss/popper.min.js' %}"></script>
            <script src="{% static 'jss/bootstrap.min.js' %}"></script>
        </body>
    </html>

flipkart/templates/cart.html
{% extends 'base.html' %}
{% load static %}

{% block metadescription %}
    Cart Page
{% endblock %}

{% block title %}
    Cart - MyBag Pvt
{% endblock %}

{% block content %}
    {% if not cart_item %}
        <div>
            <div class="text-center">
                <br>
                <h2 class="text-center my_title">
                    Your Cart is Empty
                </h2>
                <br>
                <p class="text-center">
                    <a href="{% url 'app:all_category' %}">Go to Home Page</a>
                </p>
            </div>
        </div>
    {% else %}
    <div>
        <div class="text-center">
            <br>
            <h2 class="text-center my_title">
                Your Cart
            </h2>
        </div>
    </div>
    <div class="my_row max_auto">
        <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
            <table class="table my_table">
                <thead class="my_thead">
                    <tr>
                        <th colspan="5">
                            Your Item
                        </th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in cart_item %}
                    <tr>
                        <td>
                            <a href="item.product.get_absolute_url">
                                <img src="{{item.product.image.url}}" alt="" style="width:100px; height:100px;" class="float-left rounded my_img">
                            </a>
                        </td>
                        <td class="text-left">
                            {{item.product.name}}
                            <br>
                            SKU:{{item.product.id}}
                            <br>
                            Price: $ {{item.product.price}}
                            <br>
                            Quantity:{{item.quantity}}
                        </td>
                        <td>
                            Subtotal :{{item.sub_total}}
                        </td>
                        {% if item.quantity < item.product.stock %}
                            <td>
                                <a href="{% url 'cart:add_to_cart' item.product.id %}" class="custom_a">
                                    <i class="fa fa-plus"></i>
                                </a>
                                <br>
                                <a href="{% url 'cart:cart_minus' item.product.id %}" class="custom_a">
                                   <i class="fa fa-minus"></i>
                                </a>
                                &nbsp;<br>
                                <a href="{% url 'cart:delete' item.product.id %}" class="custom_a">
                                   <i class="fas fa-trash"></i>
                                </a>
                                &nbsp;<br>
                            </td>
                        {% else %}
                            <td>&nbsp;&nbsp;
                                <a href="{% url 'cart:cart_minus' item.product.id %}" class="custom_a">
                                   <i class="fa fa-minus"></i>
                                </a>
                                &nbsp;&nbsp;
                                <a href="{% url 'cart:delete' item.product.id %}" class="custom_a">
                                   <i class="fas fa-trash"></i>
                                </a>
                                &nbsp;&nbsp;
                            </td>
                        {% endif %}
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
          <table class="table my_table">
              <thead class="my_thead">
                <tr>
                    <th>
                        CheckOut
                    </th>
                </tr>
              </thead>
              <tbody>
                <tr>
                    <td>
                        Please Review ur cart item
                    </td>
                </tr>
                <tr>
                    <td>
                        Total Amount : <strong>{{ total }}</strong>
                    </td>
                </tr>
              </tbody>
          </table>
            <div class="mx_auto">
                <a href="{% url 'app:all_category' %}" class="btn btn-secondary btn-block my_button">
                    Continue Shopping
                </a>
            </div>
        </div>
    </div>
    {% endif %}
{% endblock %}

flipkart/templates/category.html
{% extends 'base.html' %}
{% load static %}

{% block metadescription %}
    {% if categorys %}
        {{categorys.desc|truncatewords:155}}
    {% else %}
        Lorem Ipsum is simply dummy text of the printing and typesetting industry.
    {% endif %}
{% endblock %}


{% block title %}
    {% if categorys %}
        {{categorys.name}}--MyStore
    {% else %}
       Online Shopping site for all kind of products
    {% endif %}
{% endblock %}

{% block content %}
    {% if categorys %}
        <div>
            <div class="row my_row">
                <div class="mx-auto">
                    <p>
                        <a href="{% url 'app:all_category' %}">All Products </a>
                    </p>
                </div>

            </div>
        </div>
    {% endif %}
    <div class="mx-auto">
        {% if categorys %}
            <img src="{{categorys.image.url}}" alt="{{categorys.name}}" style="width:100%; height:300px;" >
    </div>
    <br>
    <div>
        <h2 class="text-center my_title">{{categorys.name}}</h2>
        <p class="text-justify" >{{categorys.desc}}</p>
    </div>
        {% else %}
    <div>
        <img class=" my_padding" src="{% static 'img/banner.jpg' %}" alt="Products" width="1400px" height="300px">
    </div>
    <br>
    <div>
        <h2 class="text-center my_title">Our Product Collections</h2>

    </div>
        {% endif %}
    <div class="container">
        <div class="row mx_auto">
            {% for i in products.object_list %}
                <div class="btm_margin col-9 col-sm-12 col-md-4 col-lg-4">
                    <div class="card text-center" style="min-width:18rem;">
                        <a href="{{i.get_url}}">
                            <img class="img_top my_img" src="{{i.image.url}}" alt="{{i.name}}" style="width:400px; height:400px" >
                        </a>
                        <div class="card_body ">
                            <h3>{{i.name}}</h3>
                            <p>{{i.price}}</p>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="mx_auto">
            {% if products.paginator.num_pages > 1 %}

            <hr>
            <div class="text-center">
                {% for pg in products.paginator.page_range %}
                    <a href="?page{{pg}}" class="btn btn-light btn-sm {% if products.number == pg %} active {% endif %}">{{pg}}</a>
                {% endfor %}
            </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

flipkart/templates/footer.html
<div class="footer navbar-fixed bottom my_footer">
    <p class="text-center">&copy; Myshop </p>
</div>

flipkart/templates/header.html
{% load static %}
<header>
    <center>
        <a href="{% url 'app:all_category' %}"><img src="{% static 'img/logo.png' %}" alt="logo" class="rounded-corners my_logo" height="100px" width="100px" align="left"></a>
    </center>
</header>

flipkart/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'app:all_category' %}"><i class="fa-solid fa-house"></i></a>
        </li>

        <li class="nav-item dropdown {% if 'app' in request.path %} active {% endif %}">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Shop
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'app:all_category' %}">All Products </a></li>
            {% for cat in links %}
            <li><a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a></li>
            {% endfor %}

          </ul>
        </li>
        {% if item_count > 0 %}
          <li class="nav-item">
            <a class="nav-link " href="{% url 'cart:cart_details' %}" ><i class="fa-solid fa-cart-shopping"></i>Cart({{item_count}})</a>
          </li>
        {% endif %}
      </ul>
      <form class="d-flex" action="{% url 'search:search_result' %}" method="get">
        {% csrf_token %}
        <input class="form-control me-2" type="search" placeholder="Search" name="q" aria-label="Search">
        <button class="btn btn-outline-success" type="submit"><i class="fa fa-search"></i></button>
      </form>
    </div>
  </div>
</nav>

<!---->

flipkart/templates/product.html
{% extends 'base.html' %}
{% load static %}

{% block metadescription %}
    {{product.desc|truncatewords:155}}
{% endblock %}

{% block title %}
    {{product.name}}--MyStore
{% endblock %}

{% block content %}
    <div class="row my_row">
        <div class="max_auto">
            <p>
                <a href="{% url 'app:all_category' %}">HOME</a> | <a href="{{ product.category.get_url }}">{{product.category}}</a>{{product.name}}
            </p>
        </div>
    </div>
    <div class="container">
        <br>
        <div class="row">
            <div class="col-12 col-sm-12 col-lg-6 text-center">
                 <div style="min-width:18rem">
                     <img src="{{product.image.url}}" alt="{{product.name}}" style="width:200px; height:200px;">
                </div>
            </div>
            <div class="col-12 col-sm-12 col-lg-6 col-md-12">
                <h2 class="my_pro_title">{{product.name}}</h2>
                <p>{{product.price}}</p>
                <p class="my_titlw">{{product.desc}}</p>
                <p class="text-justify my_row_text">{{product.heading}}</p>
                {% if product.stock <= 0 %}
                <p class="text-justify my_row_text">
                    <b>Out Of Stock</b>
                </p>
                {% else %}
                <a class="btn btn-secondary" href="{% url 'cart:add_to_cart' product.id %}">Add to cart</a>
                {% endif %}
            </div>
        </div>
    </div>


{% endblock %}

flipkart/templates/search.html
{% extends 'base.html' %}
{% load static %}

{% block metadescription %}
        Lorem Ipsum is simply dummy text of the printing and typesetting industry.
{% endblock %}

{% block title %}
        Search
{% endblock %}

{% block content %}
        <div>
                <p class="text-center my_search">
                        You Have Searched For : <b>"{{query}}"</b>
                </p>
        </div>
        <div class="container">
                <div class="row mx_auto">
                    {% for i in products %}
                        <div class="btm_margin col-9 col-sm-12 col-md-4 col-lg-4">
                            <div class="card text-center" style="min-width:18rem;">
                                <a href="{{i.get_url}}">
                                    <img class="img_top my_img" src="{{i.image.url}}" alt="{{i.name}}">
                                </a>
                                <div class="card_body ">
                                    <h3>{{i.name}}</h3>
                                    <p>{{i.price}}</p>
                                </div>
                            </div>
                        </div>
                        {% empty %}
                                <div class="mx-auto">
                                        <p class="text-center my_search">
                                                0 Result found
                                        </p>
                                </div>
                    {% endfor %}
                </div>
         </div>
{% endblock %}